"""heart/fix.py — bundle context for a specific topic and emit a Claude
Code invocation the user can paste/run.

Topics:
  ci <repo>     — the latest red CI run on that repo: dump the failing
                  job log tail + the most recent commit on main.
  drift         — current worktree drift entries: lists orphans, missing,
                  dirty.
  timing <proj> — script-timing regressions for a project: emit the
                  red/yellow list with baselines, ready for paste.

Output is plain text (color helpers applied for stderr framing, content
stripped so the user can pipe / paste safely).
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

from heart import state
from heart.heart_color import c_bold, c_fail, c_info, c_meta, c_ok, c_warn


def _gh(*args: str) -> str:
    try:
        res = subprocess.run(["gh", *args], capture_output=True, text=True, timeout=30)
        return res.stdout
    except Exception as e:
        return f"(gh failed: {e})"


def fix_ci(repo: str) -> int:
    snapshot = state.load() or {}
    repos = snapshot.get("repos", {}) or {}
    body = repos.get(repo, {})
    ci = body.get("ci_status", {}) or {}
    if not ci:
        print(c_fail(f"no CI status cached for repo '{repo}'"), file=sys.stderr)
        return 2

    print(c_bold(f"Topic: CI failure on {repo}"), file=sys.stderr)
    print(c_meta(f"  conclusion: {ci.get('conclusion')}"), file=sys.stderr)
    print(c_meta(f"  workflow:   {ci.get('workflow')}"), file=sys.stderr)
    print(c_meta(f"  sha:        {ci.get('sha')}"), file=sys.stderr)
    print(c_meta(f"  url:        {ci.get('url')}"), file=sys.stderr)
    print(file=sys.stderr)

    print(c_info("# Paste/run this in a fresh Claude Code session:"), file=sys.stderr)
    print()

    owner = "PyAutoLabs"
    name = repo
    # rhayes777 fork: PyAutoFit historically lived there; check if needed.
    # Not handled here — user can edit the prompt.
    body_lines = [
        f"# Failing CI run on {owner}/{name}",
        f"# Workflow: {ci.get('workflow')}",
        f"# URL: {ci.get('url')}",
        "",
        "Investigate the latest red CI run on this repo. Pull the failing",
        "job log tail via `gh run view <id> --log-failed`, identify which",
        "step(s) failed, and propose a minimal fix as a plan. Repo is at",
        f"~/Code/PyAutoLabs/{name}.",
    ]
    print("\n".join(body_lines))
    return 0


def fix_drift() -> int:
    snapshot = state.load() or {}
    wt = snapshot.get("worktree_drift", {}) or {}
    if not wt:
        print(c_fail("no worktree_drift cached"), file=sys.stderr)
        return 2

    orphans = wt.get("orphans", []) or []
    missing = wt.get("missing", []) or []
    dirty = wt.get("dirty", []) or []
    print(c_bold("Topic: worktree drift"), file=sys.stderr)
    print(c_meta(f"  orphans: {len(orphans)}  missing: {len(missing)}  dirty: {len(dirty)}"), file=sys.stderr)
    print(file=sys.stderr)

    print(c_info("# Paste/run this in a fresh Claude Code session:"), file=sys.stderr)
    print()
    print("# Worktree drift report")
    print()
    print("## Orphan dirs (on disk, not in active.md)")
    for o in orphans[:20]:
        print(f"  - {o.get('path')}  (real worktrees: {o.get('has_real_worktrees')})")
    print()
    print("## Missing (in active.md, not on disk)")
    for m in missing[:20]:
        print(f"  - {m.get('task')}: {m.get('path')}")
    print()
    print("## Dirty (real worktree with uncommitted changes)")
    for d in dirty[:20]:
        print(f"  - {d.get('worktree')}/{d.get('repo')}: {d.get('dirty_files')} dirty files")
    print()
    print(
        "Decide for each orphan/missing/dirty entry whether to commit, "
        "stash, or remove via `worktree_remove`. Show me the plan before "
        "executing."
    )
    return 0


def fix_dirty(repo: str) -> int:
    snapshot = state.load() or {}
    body = snapshot.get("repos", {}).get(repo, {})
    rs = body.get("repo_state", {}) or {}
    if not rs:
        print(c_fail(f"no repo_state cached for repo '{repo}'"), file=sys.stderr)
        return 2

    real = rs.get("real_files", []) or []
    noise = rs.get("noise_files", []) or []
    if not real and not noise:
        print(c_ok(f"'{repo}' has no dirty files"), file=sys.stderr)
        return 0

    print(c_bold(f"Topic: dirty working tree in {repo}"), file=sys.stderr)
    print(c_meta(f"  real source changes: {len(real)}  generated noise: {len(noise)}"), file=sys.stderr)
    print(file=sys.stderr)

    print(c_info("# Paste/run this in a fresh Claude Code session:"), file=sys.stderr)
    print()
    print(f"# Clean up the dirty working tree in {repo}")
    print(f"# Repo: ~/Code/PyAutoLabs/{repo}")
    print()
    print("## Generated artifacts (regenerated by build/simulator runs)")
    print("# These are almost always safe to revert (`git checkout -- <file>`)")
    print("# or, if they should never be tracked, add to .gitignore.")
    for n in noise[:50]:
        print(f"  - {n}")
    if len(noise) > 50:
        print(f"  ... and {len(noise) - 50} more")
    print()
    print("## Genuine source changes (review before touching)")
    print("# Decide per file: commit (if intended work), or stash/revert.")
    for r in real[:50]:
        print(f"  - {r}")
    if len(real) > 50:
        print(f"  ... and {len(real) - 50} more")
    print()
    print(
        "Decide for each file whether to commit, stash, revert, or gitignore. "
        "Revert/gitignore the generated artifacts; review the source changes "
        "individually. Show me the plan before executing anything."
    )
    return 0


def fix_timing(project: str) -> int:
    snapshot = state.load() or {}
    timing = snapshot.get("script_timing", {}) or {}
    if not timing:
        print(c_fail("no script_timing cached"), file=sys.stderr)
        return 2

    red = [r for r in timing.get("red", []) if r.get("project") == project]
    yellow = [r for r in timing.get("yellow", []) if r.get("project") == project]

    if not red and not yellow:
        print(c_ok(f"no timing regressions for project '{project}'"), file=sys.stderr)
        return 0

    print(c_bold(f"Topic: timing regressions on {project}"), file=sys.stderr)
    print(c_meta(f"  red: {len(red)}  yellow: {len(yellow)}"), file=sys.stderr)
    print(file=sys.stderr)

    print(c_info("# Paste/run this in a fresh Claude Code session:"), file=sys.stderr)
    print()
    print(f"# Script timing regressions on {project}")
    print()
    if red:
        print("## Red (>3× baseline)")
        for r in red[:20]:
            print(
                f"  - {r['file'].split('/')[-1]}: "
                f"{r['latest_seconds']:.1f}s vs baseline {r['baseline_seconds']:.1f}s "
                f"({r['ratio']}× over {r['samples']} samples)"
            )
    if yellow:
        print()
        print("## Yellow (1.5–3× baseline)")
        for r in yellow[:20]:
            print(
                f"  - {r['file'].split('/')[-1]}: "
                f"{r['latest_seconds']:.1f}s vs baseline {r['baseline_seconds']:.1f}s "
                f"({r['ratio']}×)"
            )
    print()
    print(
        "Investigate the top red regression. Profile it locally, identify "
        "what changed since the last green baseline, and propose a fix."
    )
    return 0


def main(argv: list[str]) -> int:
    if len(argv) < 2:
        print("usage: pyauto-heart fix <topic> [...]", file=sys.stderr)
        return 2
    topic = argv[1]
    args = argv[2:]
    if topic == "ci":
        if not args:
            print("usage: pyauto-heart fix ci <repo>", file=sys.stderr)
            return 2
        return fix_ci(args[0])
    if topic == "dirty":
        if not args:
            print("usage: pyauto-heart fix dirty <repo>", file=sys.stderr)
            return 2
        return fix_dirty(args[0])
    if topic == "drift":
        return fix_drift()
    if topic == "timing":
        if not args:
            print("usage: pyauto-heart fix timing <project>", file=sys.stderr)
            return 2
        return fix_timing(args[0])
    print(f"unknown topic '{topic}'", file=sys.stderr)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
